### ISSUE TITLE
Materialize и загрузка файлов

### ISSUE THREAD

**Issue by NailMukhametshin** [NailMukhametshin/MyDocuments#2]
@coursar, нашел в Materialize красивую форму для загрузки файлов https://github.com/NailMukhametshin/MyDocuments/blob/4fb20e38999d8f14c6a65fecbd6111e83246987e/src/main/resources/templates/edit.html#L32-L40, но при ее интеграции зона действия кнопки "загрузить" начинает распространяться практически на всю страницу, т.е. на странице куда бы не нажал открывается загрузка файлов.

**Comment by coursar** [comment]
заключите её в какой-нибудь контейнер с фиксированной шириной

**Comment by NailMukhametshin** [comment]
@coursar, при заключении в контейнер все начинает правильно реагировать, но при попытке сохранения документа вываливается ошибка.

**Comment by NailMukhametshin** [comment]
не актуально, исправил
